PROJECT=JSA

GENERATED_EXECUTABLES=bin/$(LC_PROJECT)-demo

GENERATED_SOURCES=$(HG_STATE_SOURCE) \
                  $(PROJECT_DEMO_SOURCE) \
                  ahven

SCRIPTS=

TEST_OUTPUT=tests/results \
            tests/unit_tests/bin/jsa-tests-run

